export const SET_QUESTIONERS = "SET_QUESTIONERS";

// Answer Error actions
export const SET_ANSWER_ERROR = "SET_ANSWER_ERROR";

export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";

// WebRTC Connection actions
export const SET_WEBRTC_CONNECTION = "SET_WEBRTC_CONNECTION";

export const SET_USER = "SET_USER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_SKILLS = "SET_SKILLS";
export const SET_NEWSKILL_NAME = "SET_NEWSKILL_NAME";
export const SET_NEWSKILL_DIFFICULTY = "SET_NEWSKILL_DIFFICULTY";
export const SET_AVAILABLESKILLOPTIONS = "SET_AVAILABLESKILLOPTIONS";
export const SET_GRPC_CLIENT = "SET_GRPC_CLIENT";
export const SET_QUESTION_MODAL = "SET_QUESTION_MODAL";
export const SET_PEER_CONNECTION = "SET_PEER_CONNECTION";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_QUESTION_DETAILS = "SET_QUESTION_DETAILS";
export const SET_FIRST_REMOTE_MESSAGE = "SET_FIRST_REMOTE_MESSAGE";
export const SET_REMOTE_CLIENT_NAME = "SET_REMOTE_CLIENT_NAME";
export const SET_TYPE_OF_USER = "SET_TYPE_OF_USER";
export const SET_RECIEVED_REWARD_RATING = "SET_RECIEVED_REWARD_RATING";
export const SET_RECIEVED_REWARD_MESSAGE="SET_RECIEVED_REWARD_MESSAGE";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_ANSWER_SOCKET = "SET_ANSWER_SOCKET";