export const SET_QUESTIONERS = "SET_QUESTIONERS";

// Answer Error actions
export const SET_ANSWER_ERROR = "SET_ANSWER_ERROR";

export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";

// WebRTC Connection actions
export const SET_WEBRTC_CONNECTION = "SET_WEBRTC_CONNECTION";

export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const SET_USER = "SET_USER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_SKILLS = "SET_SKILLS";
export const SET_NEWSKILL_NAME = "SET_NEWSKILL_NAME";
export const SET_NEWSKILL_DIFFICULTY = "SET_NEWSKILL_DIFFICULTY";
export const SET_AVAILABLESKILLOPTIONS = "SET_AVAILABLESKILLOPTIONS";
export const SET_GRPC_CLIENT = "SET_GRPC_CLIENT";
export const SET_QUESTION_TITLE = "SET_QUESTION_TITLE";
export const SET_QUESTION_DESCRIPTION = "SET_QUESTION_DESCRIPTION";
export const SET_RATING_REWARD = "SET_RATING_REWARD";
export const SET_QUESTION_MODAL = "SET_QUESTION_MODAL";